name: facial
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  camera: ^0.11.0+2
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.2.0
  firebase_storage: 12.2.0
  flutter:
    sdk: flutter
  google_mlkit_face_detection: ^0.12.0
  lottie: ^3.1.3
  path_provider: ^2.1.4
  provider: ^6.1.2
  supabase_flutter: ^2.8.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true




